name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install git-lfs (needed for Hugging Face)
        run: sudo apt-get install -y git-lfs

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git clone https://huggingface.co/spaces/marium-noor-khetran/exam-companion space_repo

      - name: Sync files to Hugging Face Space
        run: |
          rsync -av --exclude='.git' --exclude='.github' ./ space_repo/

      - name: Commit and push changes to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space_repo
          git config user.email "mariamnoor6272@gmail.com"
          git config user.name "mariumnoorkhetran"
          git add .
          git commit -m "Update from GitHub" || echo "No changes to commit"
          git push https://$HF_TOKEN@huggingface.co/spaces/marium-noor-khetran/exam-companion space main
